services:
  - type: web
    name: harxitflow
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: standard
    envVars:
      - key: HARXITFLOW_DATABASE_URL
        sync: false
      - key: HARXITFLOW_DATABASE_ECHO
        value: "false"
      - key: HARXITFLOW_DEV
        value: "false"
      - key: PORT
        value: "7860"
    healthCheckPath: /health
    restartPolicy: on-failure
