services:
  harxitflow:
    image: harxitflowai/harxitflow:latest # or another version tag on https://hub.docker.com/r/harxitflowai/harxitflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - HARXITFLOW_DATABASE_URL=postgresql://harxitflow:harxitflow@postgres:5432/harxitflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - HARXITFLOW_CONFIG_DIR=/app/harxitflow
    volumes:
      - harxitflow-data:/app/harxitflow

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: harxitflow
      POSTGRES_PASSWORD: harxitflow
      POSTGRES_DB: harxitflow
    ports:
      - "5432:5432"
    volumes:
      - harxitflow-postgres:/var/lib/postgresql/data

volumes:
  harxitflow-postgres:
  harxitflow-data:
