networks:
  dev-harxitflow:

services:
  harxitflow:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    image: dev-harxitflow
    container_name: dev-harxitflow
    restart: always
    ports:
      - "7860:7860"
      - "3000:3000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - HARXITFLOW_DATABASE_URL=postgresql://harxitflow:harxitflow@postgres:5432/harxitflow
      - HARXITFLOW_SUPERUSER=harxitflow
      - HARXITFLOW_SUPERUSER_PASSWORD=harxitflow
      - HARXITFLOW_CONFIG_DIR=/var/lib/harxitflow
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - postgres
    networks:
      -  dev-harxitflow


  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: harxitflow
      POSTGRES_PASSWORD: harxitflow
      POSTGRES_DB: harxitflow
    ports:
      - "5432:5432"
    networks:
      -  dev-harxitflow

